apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-deployments
  namespace: poc
subjects:
  - kind: ServiceAccount
    name: poc-sa
    namespace: poc
roleRef:
  kind: Role
  name: deployment-scaler
  apiGroup: rbac.authorization.k8s.io