apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: poc
  name: deployment-scaler
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "list", "update" ]